import sys
import os
from natsort import natsorted
import pandas as pd


counts_path = sys.argv[1]
out_path = sys.argv[2]
ENSG_GeneSymbol_path = sys.argv[3]  # File generated by make_ensg_gene_symbol_table.bash scipt

df_annot = pd.read_csv(ENSG_GeneSymbol_path, sep="\t", index_col=0)[["Gene"]]
df_annot = df_annot.drop_duplicates()

dfs = []
for fn in natsorted(os.listdir(counts_path)):
    if not fn.endswith(".counts"):
        continue
    
    df = pd.read_csv("{}/{}".format(counts_path, fn), sep="\t", header=None, index_col=0)
    df.columns = [fn.split(".")[0]]
    dfs.append(df)

df = pd.concat(dfs, axis=1)
df = df.join(df_annot)
df = df.loc[~df["Gene"].isna()].drop_duplicates("Gene").set_index("Gene").astype(int)

df.to_csv("{}/counts.tsv".format(out_path), sep="\t")
