import sys
import os
from natsort import natsorted

import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt


counts_path = sys.argv[1]
ENSG_GeneSymbol_path = sys.argv[2]  # File generated by make_ensg_gene_symbol_table.bash scipt
ENSG_length_path = sys.argv[3] # File generated by make_gene_length_table.bash


df_ensg_gs = pd.read_csv(ENSG_GeneSymbol_path, sep="\t", index_col=0)
df_ensg_len = pd.read_csv(ENSG_length_path, sep="\t", index_col=0)

df_annot = df_ensg_len.join(df_ensg_gs)[["Gene Symbol", "merged", "Type"]]
df_annot = df_annot.rename(columns={"merged": "length"})
df_annot = df_annot.drop_duplicates()
df_annot["Type"] = ["mitochondrion" if g.startswith("MT") else t for g, t in zip(df_annot["Gene Symbol"], df_annot["Type"])]
df_annot["Type"] = ["ribosome" if g.startswith("RP") else t for g, t in zip(df_annot["Gene Symbol"], df_annot["Type"])]

dfs = []
for fn in os.listdir(counts_path):
    if not fn.endswith(".counts"):
        continue
    
    df = pd.read_csv("{}/{}".format(counts_path, fn), sep="\t", header=None, index_col=0)
    df.columns = [fn.split(".")[0]]
    dfs.append(df)

df = pd.concat(dfs, axis=1).drop_duplicates()
df = df.join(df_annot)

for sample in df.columns[:-3]:
    summary = df[[sample, "Type"]].groupby("Type").sum()
    summary[sample] /= sum(summary[sample]) / 100
    summary = summary.sort_values(sample, ascending=False).reset_index()
    summary = summary.loc[summary[sample] >= 0.1]
    sns.barplot(x="Type", y=sample, data=summary)
    plt.xticks(rotation="45")
    plt.ylim([0, 100])
    plt.tight_layout()
    plt.savefig("{}/{}_summary.pdf".format(counts_path, sample))
    plt.close()

df = df.loc[df["Type"].isin(["protein_coding", "mitochondrion", "ribosome"])].drop(columns = ["Type"]).set_index("Gene Symbol")
df_annot = df_annot.drop_duplicates()

df = df * 10**6 / df.quantile(0.75, axis=0)
df = (df.T * 10**3 / df_annot["length"]).T

#df = .set_index("Gene Symbol")
df = np.log2(df + 1)

df.to_csv(out_table_path, sep="\t")
